### ISSUE TITLE
Считывание счетчиков наличных при закрытии смены

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#15]
Перед формированием транзакции изъятия наличных асу делает запрос количества наличных в кассе. Полученное значение подставляется в меню транзакции изъятия. Это довольно удобно для кассиров и исключает множество ошибок при вводе суммы
Сейчас на запрос с асу приходит значение 0, Можете сделать что бы по данному запросу, так же как в случае работы с ФР, возвращалась сумма наличных в кассе?

время запроса с асу:
14:33:33.073  ..........  Info......  TFPRussiaTNKShtrih..  GetGrandTotal.......  GetData(FPTR_GD_GRAND_TOTAL ) iRes=0, sGrandSales=0.00

[SHTRIH-M-OPOS-1_2022.10.04.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/9704213/SHTRIH-M-OPOS-1_2022.10.04.log)

**Comment by VitalyKravtsov2016** [comment]
Хорошо, сделаю.

**Comment by Dafafgh** [comment]
Можете посмотреть что за сумма передалась в асу? нам нужно что бы по команде GetData(8, 0, '') возвращалась сумма из SumInCashbox
[04.10.2022 18:34:33.987 ] [0000
6080] [DEBUG] Post: https://devkkm.webkassa.kz/api/cashbox/state
[04.10.2022 18:34:33.987 ] [00006080] [DEBUG] => {"Token":"e7b4139118c24cb1b31cab0c0d58f616","CashboxUniqueNumber":"SWK00032685"}

"SumInCashbox":30355.7300000000
передалось в асу:
[04.10.2022 18:34:34.426 ] [00006080] [DEBUG] ToleFiscalPrinter.GetData(8, 0, '12147874.37')=0

![1](https://user-images.githubusercontent.com/112083079/193827913-aa65b600-7445-49af-a4b8-2c709b2f9372.png)

**Comment by Dafafgh** [comment]
д

**Comment by VitalyKravtsov2016** [comment]
Это необнуляемая сумма. Сейчас сделаю, что при запросе 
GetData(FPTR_GD_GRAND_TOTAL) будет возвращаться сумма в кассе.

**Comment by Dafafgh** [comment]
у нас не получилось. видимо из-за значения параметра на скрине. Получается что разделитель смещен на 2 знака влево. приходит значение 38545.73, а в асу выводится к изъятию 385,4573
можно вывести этот параметр в настройки? или по умолчанию передавать значение "2"?

17:14:37.914  ..........  ..........  TIOSystemLink.......  GetGrandTotal.......  Leave Result = 385,4573
17:14:37.914  ..........  Info......  TBaseTenderDlg......  KbdEditEditChange...  Value is 385,00 тг

17:14:37.913  ..........  Info......  TFPRussiaTNKShtrih..  GetGrandTotal.......  GetData(FPTR_GD_GRAND_TOTAL ) iRes=0, sGrandSales=38545.73

![1](https://user-images.githubusercontent.com/112083079/194048536-fa38d8b5-eb0c-41a4-8442-0c517285eb5d.png)
