### ISSUE TITLE
номер транзакции АСУ ExternalCheckNumber

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#16]
а это поле заполняет OPOS? заказчик хочет что бы мы передавали в этом поле номер чека АСУ(по протоколу оно для этого и предназначено)
"ExternalCheckNumber":"A1C90419-823C-44C6-919F-AB6934905D81"

и второй вопрос, заказчик хочет видеть в АСУ фискальный признак чека "CheckNumber"(рис.)
можно будет передавать этот номер в АСУ?

![55d58a51-922b-4c83-8d94-03468b5112f5](https://user-images.githubusercontent.com/112083079/193837001-a9a30339-372d-466c-b78e-47ebe3e418eb.jpg)

**Comment by VitalyKravtsov2016** [comment]
Сейчас CheckNumber выдается при запросе getData(FPTR_GD_RECEIPT_NUMBER)

**Comment by Dafafgh** [comment]
появились вопросы:
Тут нужно передавать номер текущей транзакции в кассе, или номер текущей транзакции полученной с помощью getData(FPTR_GD_RECEIPT_NUMBER)?

И какое значение нужно передать в:
directIO(DIO_SET_DRIVER_PARAMETER, DriverParameterFiscalSign, Value) ?

**Comment by VitalyKravtsov2016** [comment]
1. С версии драйвера 0.16 запрос getData(FPTR_GD_RECEIPT_NUMBER) будет возвращать сквозной номер документа
2. В команде directIO(DIO_SET_DRIVER_PARAMETER, DriverParameterExternalCheckNumber, Value) можно передавать 
    номер чека из приложения. Можно не вызывать этот метод, драйвер сам создаст этот номер. 
3. В параметр DriverParameterFiscalSign можно передавать любое значение, оно только печатается на чеке.

**Comment by Dafafgh** [comment]
1. По запросу getData(FPTR_GD_RECEIPT_NUMBER) нам нужно получать CheckNumber

**Comment by Dafafgh** [comment]
сейчас GetData(FPTR_GD_RECEIPT_NUMBER) возвращает не "CheckNumber"

16:07:45.321  ..........  Info......  TFPRussiaTNKShtrih..  GetStrReceiptNumber.  GetData(FPTR_GD_RECEIPT_NUMBER) sData=**271**, iRes=0

[22.11.2022 16:07:45.336 ] [00006364] [DEBUG] ToleFiscalPrinter.GetData(3, 0, '')
[22.11.2022 16:07:45.336 ] [00006364] [DEBUG] ToleFiscalPrinter.GetData(3, 0, '271')=0

"CheckNumber":"**1149917291693**"


[STOREPOINTIO-20221122.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/10067678/STOREPOINTIO-20221122.log)
