### ISSUE TITLE
номер Z-отчета

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#17]
Еще мы сохраняем в БД номер Z-отчета. Можно сделать что бы по запросу Z-отчета передавалось значение поля ShiftNumber?

18:34:48.332  ..........  Info......  TFPRussiaTNKShtrih..  GetFiscalZNumber....  GetData(FPTR_GD_Z_REPORT) sData=0.00, Result=0

"ShiftNumber":197

[SHTRIH-M-OPOS-1_2022.10.04.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/9707520/SHTRIH-M-OPOS-1_2022.10.04.log)
![22](https://user-images.githubusercontent.com/112083079/193838250-9668fd86-2334-4709-aea7-31a4016f0454.png)

**Comment by VitalyKravtsov2016** [comment]
Сейчас сделаю.
