### ISSUE TITLE
порядок установки

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#28]
у себя на ПК поставил:
OposShtrih_1.13_573.exe
OposWebkassa_1.13_17.exe

при нажатии "изменить" выдает ошибку, в чем может быть проблема?

[OLEforRetail.zip](https://github.com/VitalyKravtsov2016/OposWebkassa/files/10066630/OLEforRetail.zip)
![Безымянный](https://user-images.githubusercontent.com/112083079/203296199-e59455a1-04bf-4178-8f1c-f8aa4d6b133b.png)

**Comment by VitalyKravtsov2016** [comment]
Это потому, что это логическое устройство от другого драйвера. 
По хорошему наверное нужно показывать только свои устройства. 
Подумаю.
