### ISSUE TITLE
Альтернативные адреса сервера

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#29]
Добрый день
Сейчас OPOS отправляет чеки на один адрес, или в случае получения ошибки по основному адресу перебирает альтернативные? 

[01.12.2022 14:28:44.127 ] [00000356] [ERROR] OPOS_E_FAILURE, 0, "Socket Error # 10060
Connection timed out."

![image](https://user-images.githubusercontent.com/112083079/205005585-ff94ddad-f731-4610-9f4f-4899a16c41a3.png)
[SHTRIH-M-OPOS-1_2022.12.01.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/10131044/SHTRIH-M-OPOS-1_2022.12.01.log)

**Comment by VitalyKravtsov2016** [comment]
Добрый день. 
Сейчас отправляет только на один адрес. 
Попробую сделать перебор адресов.

**Comment by VitalyKravtsov2016** [comment]
Интересно, как это проверять?

**Comment by Dafafgh** [comment]
хороший вопрос, написал Ардаку, пока еще молчит.
еще задал вопрос по автономному режиму, как работает их Модуль Печати

**Comment by Dafafgh** [comment]
наверное переборка адресов не очень актуальна. выяснилось что при потере связи нужно работать с локальным сервером. в архиве файлы сервера, инструкции(а так же обновленное описание API v35)

на стенде локальный сервер установился успешно

https://disk.yandex.ru/d/yB8cvyH2j5Wsig

**Comment by VitalyKravtsov2016** [comment]
Значит пока замечаний нет?

**Comment by Dafafgh** [comment]
по названию скидки есть вопрос, сейчас создам. мы используем несколько названий скидок. например скидка "Округление", "Округление по акции" и обычная "скидка". хотелось бы так же как сейчас печатать название скидки в чеке

**Comment by VitalyKravtsov2016** [comment]
Поправил
https://github.com/VitalyKravtsov2016/OposWebkassa/releases/tag/0.21

**Comment by Dafafgh** [comment]
на новой версии произошла ошибка:
[02.12.2022 14:45:35.211 ] [00007688] [DEBUG] <= {"Errors":[{"Code":9,"Text":"Значение поля Discount не может быть отрицательным или превышать 9 целых разрядов"}]}
[02.12.2022 14:45:35.211 ] [00007688] [ERROR] OPOS_E_EXTENDED, 309, "Значение поля Discount не может быть отрицательным или превышать 9 целых разрядов"



п.с. в обычном режиме в чеке печатается переданное название скидки(рис.)
[02.12.2022 14:45:34.899 ] [00007688] [DEBUG] ToleFiscalPrinter.PrintRecItemAdjustment(1, 'Округление', 1, 4)
[02.12.2022 14:45:34.899 ] [00007688] [DEBUG] ToleFiscalPrinter.PrintRecItemAdjustment(1, 'Округление', 1, 4)=0

![IMG_20221202_115021](https://user-images.githubusercontent.com/112083079/205253907-8ec70d74-d973-46d4-a064-c2384caf1d09.jpg)
