### ISSUE TITLE
ошибка при вхоже в OPOS Setup

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#31]
В чем может быть причина ошибки?

[SHTRIH-M-OPOS-1_2022.12.09.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/10193332/SHTRIH-M-OPOS-1_2022.12.09.log)
![Безымянный](https://user-images.githubusercontent.com/112083079/206665746-499745ec-f443-4d46-ba7f-0c761e94294c.png)
[Windows.zip](https://github.com/VitalyKravtsov2016/OposWebkassa/files/10193337/Windows.zip)

**Comment by VitalyKravtsov2016** [comment]
Сейчас поправлю.
