### ISSUE TITLE
Отличие чека продажи от возврата

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#34]
заметили что печатная форма чеков продажи и возврата особо ничем не отличаются. нет типа операции "продажа" и "возврат". можно это добавить в чек?

[SHTRIH-M-OPOS-1_2022.12.09.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/10195023/SHTRIH-M-OPOS-1_2022.12.09.log)
![IMG_20221209_160455](https://user-images.githubusercontent.com/112083079/206709315-30254f23-2c60-4139-8b3e-ed0dbb20c4f1.jpg)

**Comment by VitalyKravtsov2016** [comment]
Да, сейчас сделаю.
