### ISSUE TITLE
проверка SWK

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#38]
на стенде заказчика не проходит проверка подключения:

![11](https://user-images.githubusercontent.com/112083079/209533986-9e218537-66e4-4d43-9dfb-c673d9f446a9.png)

хотя на сайт под его логин\паролем заходит и в списке отображается SWK00033053(рис.)
логи при проверке не пишутся. версия 26

**Comment by Dafafgh** [comment]
лог по авторизации
devkkm.webkassa.kzapi/
смущает слитность записи в логе. ну и ошибка при подключении та же

[10.01.2023 14:48:09.138 ] [00012696] [DEBUG] Post: https://devkkm.webkassa.kzapi/Authorize/WithEmployeeInfo
[10.01.2023 14:48:09.138 ] [00012696] [DEBUG] => {"Login":"Adiн.kz","Password":"ннннн"}

**Comment by VitalyKravtsov2016** [comment]
Там есть ошибка. 
По умолчанию адрес сервера: "https://devkkm.webkassa.kz/"
Если задать адрес "https://devkkm.webkassa.kz", то работать не будет. 
К этому адресу дописывается строка запроса.

**Comment by VitalyKravtsov2016** [comment]
Поправил:
https://github.com/VitalyKravtsov2016/OposWebkassa/releases/tag/0.29

**Comment by Dafafgh** [comment]
проверили, установили на стенд заказчика
