### ISSUE TITLE
OPOS 573

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#39]
вопрос по опос 573. на азс произошел вылет. можете посмотреть в чем проблема?

[30.12.2022 00:35:10.381 ] [00004628] [DEBUG] ToleFiscalPrinter.PrintRecTotal(46000, 0, '2')=0
[30.12.2022 00:35:10.383 ] [00004628] [DEBUG] ToleFiscalPrinter.PrintRecMessage('VLife Клуб        №**************gV1B')
Exception EAccessViolation: Access violation at address 772D56B5 in module 'ntdll.dll'. Read of address 00000000 (OS Exception)
[SHTRIH-M-OPOS-1_2022.12.30.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/10325821/SHTRIH-M-OPOS-1_2022.12.30.log)

**Comment by VitalyKravtsov2016** [comment]
Скорее всего в драйвере есть небольшая утечка памяти и 
при длительной работе выделение памяти больше не работает. 
Ошибка происходит при вызове RtlAllocateHeap, которая выделяет память в куче. 
Важно понять, насколько часто происходит эта ошибка. 
Утечку памяти поищу.

**Comment by VitalyKravtsov2016** [comment]
Хорошо бы эту ошибку перенести в проект OPOS:
https://github.com/shtrih-m/opos/issues

**Comment by Dafafgh** [comment]
проблема редкая. если повторится создам в другом проекте и попробую перенести эту тему
