### ISSUE TITLE
Печать QR. Задвоение шапки и подвала

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#40]
Добрый день
на стенде заказчика в чеке не печатается QR и задвоены шапка с подвалом. можете посмотреть почему?

[13.01.2023 16:53:40.069 ] [00000556] [DEBUG] ToleFiscalPrinter.PrintRecMessage('Транз.:      11822 ')
[13.01.2023 16:53:40.069 ] [00000556] [DEBUG] ToleFiscalPrinter.PrintRecMessage('Транз.:      11822 ')=0

красным выделял заказчик, к письму не относится

[SHTRIH-M-OPOS-1_2023.01.13.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/10424702/SHTRIH-M-OPOS-1_2023.01.13.log)
![Безымянный](https://user-images.githubusercontent.com/112083079/212652861-3fc1be4d-7d77-49ac-814a-2ea61b6cd373.png)

**Comment by VitalyKravtsov2016** [comment]
QR не печатается всегда?

**Comment by VitalyKravtsov2016** [comment]
Как часто не печатается QR код?

**Comment by VitalyKravtsov2016** [comment]
А можно тестовый чек посмотреть - там параметры и версии ПО печатаются.

**Comment by VitalyKravtsov2016** [comment]
В программе настройки принтера есть возможность разрешить или запретить печать двумерных штрих-кодов. 
Можно попробовать включить.

**Comment by VitalyKravtsov2016** [comment]
Добрый день. 
 
Да, сегодня сделаю.
Будет параметр как печатать QR код: через команду или в графике. 
 
 
 
С уважением,
Кравцов Виталий, программист
рабочий   : (495) 787-60-90, добавочный 295
мобильный : 8 (916) 819-13-24
Наш сайт: www.shtrih-m.ru
 ***@***.***> ***@***.***
icq: 157741050

  _____

**Comment by VitalyKravtsov2016** [comment]
Поправил:
https://github.com/VitalyKravtsov2016/OposWebkassa/releases/tag/0.31
