### ISSUE TITLE
Длина чека

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#41]
Клиент задал вопрос по длине чека. Можно ли его сделать компактней, изменив меж строчные интервалы, шрифт? И еще вопрос по поводу отрезки. От места отрезки до текста шапки и после текста подвала до места отрезки довольно много "пустой ленты". Можно ли сместить отрезку к тексту шапки\подвала?

![7f48d160-4f53-4631-9d0e-9b184ecd62e1](https://user-images.githubusercontent.com/112083079/216265498-67511b14-2355-46cd-8766-915caeda555c.jpg)

**Comment by VitalyKravtsov2016** [comment]
Добрый день. 
Да, можно поменять и шрифт и межстрочное расстояние. 
По-хорошему нужно сделать формат чека. 
Постараюсь сегодня сделать.
