### ISSUE TITLE
не печатается чек, не сохраняются настройки принтера

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#48]
на версии 35 не сохраняются настройки печатного принтера. и чек не печатается

[04.08.2023 14:05:31.605 ] [00006004] [ERROR] OPOS_E_FAILURE, 0, "Bitmap image is not valid"
[04.08.2023 14:05:31.605 ] [00006004] [ERROR] Failed to print document, Bitmap image is not valid

[SHTRIH-M-OPOS-1_2023.08.04.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/12258762/SHTRIH-M-OPOS-1_2023.08.04.log)
![Безымянный](https://github.com/VitalyKravtsov2016/OposWebkassa/assets/112083079/f25ddc84-2055-490a-8184-dba7862187b1)

**Comment by VitalyKravtsov2016** [comment]
Сейчас проверю.

**Comment by VitalyKravtsov2016** [comment]
Почему нет названия принтера? 
В системе установлен принтер?
Можно увидеть список принтеров системы?

**Comment by Dafafgh** [comment]
при закрытии OPOS настройки слетают(рис.1), при выставлении настроек(рис.2) все нормально. при перезаходе они не сохраняются(рис.1)

![1](https://github.com/VitalyKravtsov2016/OposWebkassa/assets/112083079/f819510b-5510-456a-8526-f546ff007203)
![2](https://github.com/VitalyKravtsov2016/OposWebkassa/assets/112083079/abdd497e-b8ce-4a63-8d41-9cc9b4d273f9)

**Comment by VitalyKravtsov2016** [comment]
Поправил:
https://github.com/VitalyKravtsov2016/OposWebkassa/releases/tag/0.36

**Comment by Dafafgh** [comment]
настройки сохраняются, но чек не напечатался
[04.08.2023 15:26:37.791 ] [00004704] [ERROR] OPOS_E_FAILURE, 0, "Bitmap image is not valid"
[04.08.2023 15:26:37.791 ] [00004704] [ERROR] Failed to print document, Bitmap image is not valid

**Comment by VitalyKravtsov2016** [comment]
Странно, сейчас разберусь

**Comment by VitalyKravtsov2016** [comment]
Пока я разбираюсь с ошибкой, можно включить печать QR кода в виде ESC команд.

**Comment by VitalyKravtsov2016** [comment]
Поправил: https://github.com/VitalyKravtsov2016/OposWebkassa/releases/tag/0.37

**Comment by Dafafgh** [comment]
на 34 с настройкой в виде графики печатает, на 35+ нет

в34
[04.08.2023 20:20:33.023 ] [00007668] [DEBUG] ToleFiscalPrinter.PrintRecMessage('ID:      30661 ')
[04.08.2023 20:20:33.023 ] [00007668] [DEBUG] ToleFiscalPrinter.PrintRecMessage('ID:      30661 ')=0

в37
[04.08.2023 20:22:08.730 ] [00005632] [DEBUG] ToleFiscalPrinter.PrintRecMessage('ID:      30662 ')
[04.08.2023 20:22:08.730 ] [00005632] [DEBUG] ToleFiscalPrinter.PrintRecMessage('ID:      30662 ')=0

![1212](https://github.com/VitalyKravtsov2016/OposWebkassa/assets/112083079/c38f85c4-118d-4c87-b5ad-cbd922b3b95a)

**Comment by VitalyKravtsov2016** [comment]
Поправил:
https://github.com/VitalyKravtsov2016/OposWebkassa/releases/tag/0.38

**Comment by Dafafgh** [comment]
Добрый день
несколько вопросов:
1. Пробел после "х" в кол-во на цену. На рисунке зеленым подчеркнуто место, где знак "х" сливается с ценой товара, хотелось бы разделить "х" и цену товара пробелом
2. Добавить валюту после цены. В туже строку с ценой на количество хотелось бы добавить валюту цены(в нашем случае тг)
3. PrintRecMessage и шапка\подвал не редактируется. Хотелось бы редактировать размер шрифта. А для PrintRecMessage и положение в чеке(<Alignment>0</Alignment>) 
4. При выставлении настройки использования формата чека перестает печататься QR
5. В теле чека тоже нужна возможность изменить шрифт. Сейчас есть возможность выбрать шаблоны. С текущими шаблонами в чеке шрифт хорошего размера, но клиент хочет его уменьшить для сокращения общей длины чека
6. Можно ли сделать настройку изменения межстрочного интервала?
7. Единица измерения товара сейчас статическая "кг". Тут нужно использовать переменную единицу измерения, которую передает приложение

[08.08.2023 17:37:14.162 ] [00006892] [DEBUG] ToleFiscalPrinter.PrintRecMessage('ID:      30675 ')
[08.08.2023 17:37:14.162 ] [00006892] [DEBUG] ToleFiscalPrinter.PrintRecMessage('ID:      30675 ')=0

![1691499793348](https://github.com/VitalyKravtsov2016/OposWebkassa/assets/112083079/1556f5e4-3abc-4358-a054-ae1905ffd864)

**Comment by VitalyKravtsov2016** [comment]
1. Хотелось бы на каждую ошибку заводить отдельное обращение, Issue
2. Пробел после "х" в кол-во на цену - поправлю
3. Добавить валюту после цены - сделаю настройку названия валюты
4. PrintRecMessage и шапка\подвал не редактируется. - шапка и подвал чека настраиваются.
5. При выставлении настройки использования формата чека перестает печататься QR - добавлю
6. В теле чека тоже нужна возможность изменить шрифт - сделаю
7. Можно ли сделать настройку изменения межстрочного интервала - сделаю
8. Единица измерения товара сейчас статическая "кг" - сейчас так и сделано

**Comment by VitalyKravtsov2016** [comment]
Поправил: https://github.com/VitalyKravtsov2016/OposWebkassa/releases/tag/0.39
