### ISSUE TITLE
Настройка межстрочного интервала

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#50]
Можете показать где находится настройка межстрочного интервала?

**Comment by VitalyKravtsov2016** [comment]
Добрый день. 
Закладка 02. Принтер -> Межстрочный интервал

**Comment by VitalyKravtsov2016** [comment]
Также можно межстрочный интервал задавать в шаблоне чека. 
То есть в одном чеке можно использовать разные значения межстрочного интервала.
