### ISSUE TITLE
Изменение размера шрифта

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#53]
сейчас для управления размером шрифта доступны несколько стилей. можно добавить и управление размером шрифта?(интересует изменение самого размера в меньшую сторону)

[SHTRIH-M-OPOS-1_2023.08.21.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/12395493/SHTRIH-M-OPOS-1_2023.08.21.log)

**Comment by Dafafgh** [comment]
эта настройка влияет на количество символов в строке

![111](https://github.com/VitalyKravtsov2016/OposWebkassa/assets/112083079/5385b4fb-93e9-4bed-93e4-4bb75e5f00b1)

**Comment by VitalyKravtsov2016** [comment]
Эта настройки влияет не только на количество символов в строке. но и на высоту строки.
В принтере RP80 есть 2 шрифта:
0, Font A (12x24)
1, Font B (9x17)
Шрифт A высотой 24 точки, шрифт B высотой 17 точек
