### ISSUE TITLE
Успешный запуск АСУ, при некорректных настройках OPOS

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#62]
В настройках OPOS намеренно изменили порт подключения на неправильный(1332 -> 13321), соединение с локальным сервером не проходит. Можно сделать что бы АСУ в таком случае получала ошибку сразу же на момент загрузки приложения? сейчас ошибка выявляется только при попытке продажи товара

[25.01.2024 21:23:49.268 ] [00002560] [DEBUG] Post: http://localhost:13321/api/Authorize
[25.01.2024 21:23:49.268 ] [00002560] [DEBUG] => {"Login":"apykhtin@ibts.ru","Password":"Kassa123!"}
[25.01.2024 21:23:50.284 ] [00002560] [ERROR] Socket Error # 10061
Connection refused.
[25.01.2024 21:23:53.284 ] [00002560] [DEBUG] TPrinterParametersReg.SaveUsrParameters('SHTRIH-M-OPOS-1')

21:24:09.691  ..........  ..........  TIOSystem...........  InitDevice..........  Claim(10) "SHTRIH-M-OPOS-1" = OPOS_SUCCESS

[SHTRIH-M-OPOS-1_2024.01.25.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/14054084/SHTRIH-M-OPOS-1_2024.01.25.log)
[STOREPOINTIO-20240125.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/14054092/STOREPOINTIO-20240125.log)

**Comment by VitalyKravtsov2016** [comment]
Сделал подключение к серверу в методе Claim:
https://github.com/VitalyKravtsov2016/OposWebkassa/releases/tag/0.53

**Comment by Dafafgh** [comment]
сейчас перестало с корректными настройками загружаться 




14:28:15.714  ..........  ..........  TIOSystem...........  InitDevice..........  Claim(10) "SHTRIH-M-OPOS-1" = OPOS_E_FAILURE
14:28:15.714  ..........  ..........  TIOSystem...........  InitDevices.........  Returned result 111

**Comment by VitalyKravtsov2016** [comment]
Поправил:
https://github.com/VitalyKravtsov2016/OposWebkassa/releases/tag/0.54
