### ISSUE TITLE
Стенд, ошибка "заполните поле" при claim

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#63]
не понятно с чем связана ошибка "Заполните поле". в логах нет информации по ошибке

[debug20240318.txt](https://github.com/VitalyKravtsov2016/OposWebkassa/files/14634078/debug20240318.txt)
[info20240318.txt](https://github.com/VitalyKravtsov2016/OposWebkassa/files/14634079/info20240318.txt)
[SHTRIH-M-OPOS-1_2024.03.18.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/14634080/SHTRIH-M-OPOS-1_2024.03.18.log)
![Безымянный](https://github.com/VitalyKravtsov2016/OposWebkassa/assets/112083079/45e9b13b-cf9d-4bd2-9611-753d39366ba5)

**Comment by VitalyKravtsov2016** [comment]
Поправил:
https://github.com/VitalyKravtsov2016/OposWebkassa/releases/tag/0.55
