### ISSUE TITLE
Значение параметра. колво знаков после запятой

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#66]
Заметили что сейчас передается не та сумма. С чеками все в порядке, касается только внесение\изъятие + Z-отчет. При одном значении настройки асу получает неправильную сумму внесений\изъятий(/100), но правильную сумму Z-отчета. При другом наоборот, правильные суммы внесений\изъятий, но неправильную сумму Z-отчета(х100)

мы используем только значение "2". но при таком значении сумма продаж по Z-отчету приходит 23600, а правильная 236. можно сделать что бы при таком значении параметра драйвер не умножал *100 сумму продаж по Z-отчету(но по внесение\изъятие умножение *100 осталось)?

при значении 2(правильные суммы внесений\изъятий, но неправильную сумму Z-отчета):
[23.05.2024 18:47:50.401 ] [00006512] [DEBUG] ToleFiscalPrinter.GetData(8, 0, '1093600')=0

18:47:50.401  ..........  Info......  TFPWebKassa.........  GetGrandTotal.......  GetData(FPTR_GD_GRAND_TOTAL ) iRes=0, sGrandSales=_**1093600**_

18:47:50.401  ..........  ..........  TIOSystemLink.......  GetGrandTotal.......  Leave Result = **_10936_**

[23.05.2024 18:49:05.561 ] [00006512] [DEBUG] ToleFiscalPrinter.GetData(2, 0, '**_23600_**')=0

при значении 0(неправильную сумму внесений\изъятий(/100), но правильную сумму Z-отчета):
[23.05.2024 18:57:08.022 ] [00007060] [DEBUG] ToleFiscalPrinter.GetData(8, 0, '11172')=0

18:57:08.022  ..........  Info......  TFPWebKassa.........  GetGrandTotal.......  GetData(FPTR_GD_GRAND_TOTAL ) iRes=0, sGrandSales=11172

18:57:08.022  ..........  ..........  TIOSystemLink.......  GetGrandTotal.......  Leave Result = **_111,72_**

[23.05.2024 18:58:24.697 ] [00007060] [DEBUG] ToleFiscalPrinter.GetData(2, 0, '**_236_**')=0

![1](https://github.com/VitalyKravtsov2016/OposWebkassa/assets/112083079/4abe233b-374e-46ba-9868-71e2e55e4727)
[SHTRIH-M-OPOS-1_2024.05.23.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/15418305/SHTRIH-M-OPOS-1_2024.05.23.log)
[STOREPOINTIO-20240523.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/15418306/STOREPOINTIO-20240523.log)

**Comment by VitalyKravtsov2016** [comment]
Посмотрел лог. 
В основном там стоит AmountDecimalPoint=0, а на сервере 2.
В такой конфигурации работать не будет, так ставить не нужно. 
По умолчанию в драйвере AmountDecimalPoint=2. 
С какой целью изменили - непонятно. 
Что неправильно передается при AmountDecimalPoint=2?

**Comment by Dafafgh** [comment]
AmountDecimalPoint= менял я для сравнения. мы используем только значение 2
при значении 2 передается неправильная сумма продаж по Z_отчету. передается 23600, а по факту продаж было на 236

[23.05.2024 18:49:05.561 ] [00006512] [DEBUG] ToleFiscalPrinter.GetData(2, 0, '23600')=0

не сказать что она неправильная, нам просто нужно тут 236, тогда асу запишет корректную сумму в свою БД

**Comment by Dafafgh** [comment]
но при значении AmountDecimalPoint=0 и фактических продаж на те же 236 возвращается 236(а не 23600 как при AmountDecimalPoint=2)
18:58:24.697  ..........  Info......  TFPWebKassa.........  GetDailyTotal.......  GetData(FPTR_GD_DAILY_TOTAL ) iRes=0, sDailySales=236

**Comment by Dafafgh** [comment]
а отдельную настройку для передачи в асу суммы продаж по Z-отчету можно добавить?
или даже не настройку, что бы FPTR_GD_DAILY_TOTAL всегда возвращал в асу значение в 100 раз меньше?

**Comment by VitalyKravtsov2016** [comment]
Теоретически это возможно.
Все значения в драйвере должны возвращаться одинаково.
Насколько я понимаю, можно поменять приложение.

**Comment by Dafafgh** [comment]
можно и приложение. но приложение работает уже с немалым количеством опос-драйверов и очень не хотелось на каком то другом драйвере увидеть неправильную сумму продаж по з-отчету, т.к. изменение в приложении(для одного только драйвера OPOSWebkassa) может повлечь за собой ошибки в работе с каким либо другим драйвером

**Comment by VitalyKravtsov2016** [comment]
Поправлю.

**Comment by VitalyKravtsov2016** [comment]
Поправил:
https://github.com/VitalyKravtsov2016/OposWebkassa/releases/tag/0.62

**Comment by Dafafgh** [comment]
На этой версии с AmountDecimalPoint=2 чеки распечатались как с AmountDecimalPoint=0. По сумме продаж Z-отчета все хорошо, по сумме изъятия 118,8, а не 11880. Можно теперь к сумме наличных в кассе для изъятия запятую сместить на два знака вправо, что бы асу у себя преобразовала в 11880?

[27.05.2024 17:49:39.840 ] [00001716] [DEBUG] ToleFiscalPrinter.GetData(8, 0, '11880.00')=0

17:49:39.840  ..........  Info......  TFPWebKassa.........  GetGrandTotal.......  GetData(FPTR_GD_GRAND_TOTAL ) iRes=0, sGrandSales=11880.00

асу вывела сумму 119:
17:49:39.840  ..........  ..........  TIOSystemLink.......  GetGrandTotal.......  Leave Result = **118,8**


[27.05.2024 17:49:45.810 ] [00001716] [DEBUG] ToleFiscalPrinter.GetData(2, 0, '236.00')=0
17:49:45.810  ..........  Info......  TFPWebKassa.........  GetDailyTotal.......  GetData(FPTR_GD_DAILY_TOTAL ) iRes=0, sDailySales=236.00

**Comment by VitalyKravtsov2016** [comment]
Насколько я понимаю, приложение по-разному обрабатывает 
разные запросы getData. Разве это правильно?

**Comment by Dafafgh** [comment]
есть подозрение что правильно, потому что наш ФР(РФ) возвращает такие значения:

[25.05.2023 00:02:58.343 ] [00000164] [DEBUG] ToleFiscalPrinter.GetData(8, 0, '2634160')=0 (без разделителя?)(при фактической сумме 26341.60)
[25.05.2023 00:03:02.671 ] [00000164] [DEBUG] ToleFiscalPrinter.GetData(2, 0, '37857.00')=0(с разделителем?)(при фактической сумме '37857.00)

а вебкасса возвращает "однообразней"
