### ISSUE TITLE
от вебкассы №2 ExternalCheckNumber 

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#73]
второй вопрос
"
Если используются небезопасные внешние номера чеков (ExternalCheckNumber), то при переходе на чек по ссылке может запрашивать капчу. В поле ExternalCheckNumber нужно передавать GUID.
у вас сейчас 
https://my.webkassa.kz/spa-ui/ticket?chb=SWK00454493&sh=208&extnum=2979372
Должно быть что то типа такого 941726a8-c735-4b52-85c3-2550137a327f
https://my.webkassa.kz/spa-ui/ticket?chb=SWK00473660&sh=60&extnum=941726a8-c735-4b52-85c3-2550137a327f
"

**Comment by VitalyKravtsov2016** [comment]
В драйвере сделана возможность записи внешнего номера чека. 
Если этот номер приложение не установило, но драйвер сгенерирует GUID.
В данном случае этот номер установило приложение.
