### ISSUE TITLE
Ошибка "неверное состояние принтера"

### ISSUE THREAD

**Issue by ErmacTheSoul** [VitalyKravtsov2016/OposWebkassa#76]
Добрый день, заказчик столкнулся с ошибкой 114/207 в работе OPOS, интегрированного с Webkassa:

[08.07.2024 21:45:27.491 ] [00013864] [ERROR] OPOS_E_EXTENDED, OPOS_EFPTR_WRONG_STATE, "Wrong printer state"
[08.07.2024 21:45:27.491 ] [00013864] [DEBUG] ToleFiscalPrinter.EndFiscalReceipt(False)=114

с чем может быть связана данная ошибка?

[SHTRIH-M-OPOS-1_2024.07.08.log.zip](https://github.com/user-attachments/files/16140319/SHTRIH-M-OPOS-1_2024.07.08.log.zip)

версия OPOS 1.13.0.66

**Comment by VitalyKravtsov2016** [comment]
Добрый день. 
В логе нет вызова printRecTotal. 
Нужно вызывать printRecTotal, даже если чек нулевой. 

После вызова beginFiscalReceipt драйвер в состоянии FPTR_PS_FISCAL_RECEIPT. 
В этом состоянии можно добавлять позиции в чек. 
После вызова printRecTotal драйвер переходит в состояние FPTR_PS_FISCAL_RECEIPT_TOTAL,
если чек не полностью оплачен или в состояние FPTR_PS_FISCAL_RECEIPT_ENDING, если 
чек оплачен полностью. В состоянии FPTR_PS_FISCAL_RECEIPT_TOTAL возможен только вызов printRecTotal.
В состоянии FPTR_PS_FISCAL_RECEIPT_ENDING возможен вызов endFiscalReceipt.

**Comment by ErmacTheSoul** [comment]
ок, напишем разработчику АСУ
