### ISSUE TITLE
ндс 0%

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#8]
Продали товар с НДС 0%. в чеке пишется строка с ндс 12%(рис.), в таблице соответствия строка с ндс 0% заведена
в чеке некорректно отображена строка: "в т.ч. НДС 12%:". в случае продажи товара с ндс 0% в чеке тоже должно выводиться ндс 0%

[27.08.2022 11:24:06.201 ] [00003064] [DEBUG] ToleFiscalPrinter.PrintRecItem('Жальгирис Сыр 40% 180г VILVI', 885, 1000, 2, 885, 'шт')
[27.08.2022 11:24:06.203 ] [00003064] [DEBUG] ToleFiscalPrinter.PrintRecItem('Жальгирис Сыр 40% 180г VILVI', 885, 1000, 2, 885, 'шт')=0

[SHTRIH-M-OPOS-1_2022.08.27.log](https://github.com/VitalyKravtsov2016/OposWebkassa/files/9476046/SHTRIH-M-OPOS-1_2022.08.27.log)
![IMG_20220902_105110](https://user-images.githubusercontent.com/112083079/188087575-b7173769-2863-4c59-a6c0-006441a5f048.jpg)
![1](https://user-images.githubusercontent.com/112083079/188087668-f05ac85b-3a78-40c1-b670-57e12918a461.jpg)

**Comment by VitalyKravtsov2016** [comment]
Дело в том, что эту строку формирует WebKassa. По логу можете посмотреть, какой json передает драйвер и что возвращает WebKassa. Протокол WebKass есть тут: https://github.com/VitalyKravtsov2016/OposWebkassa/blob/master/doc/Webkassa/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%20API%20Webkassa%20General_v39.pdf

Драйвер передает в налогах 0, то есть без налогов (TaxTypeNoTax = 0).
Почему так пишет WebKassa я не знаю. 
Вероятно нужно формировать текст чека в драйвере.
