### ISSUE TITLE
OPOS_E_FAILURE, 0, "List index out of bounds (0)"

### ISSUE THREAD

**Issue by ErmacTheSoul** [VitalyKravtsov2016/OposWebkassa#80]
[SHTRIH-M-OPOS-1_2024.09.01.log.zip](https://github.com/user-attachments/files/17397781/SHTRIH-M-OPOS-1_2024.09.01.log.zip)

Виталий, добрый день.
у одного из наших заказчиков при попытке пробить чек по банку на сумму 4680 выходила ошибка:

[01.09.2024 09:24:10.807 ] [00015176] [ERROR] OPOS_E_FAILURE, 0, "List index out of bounds (0)"

в чеке присутствует скидка

подскажите, по какой причине выходила данная ошибка и как её исправить? возможно требуется доработка OPOS, правда версия у них тогда была не самая новая

File version         : 1.13.0.67

возможно такую ошибку уже исправляли

**Comment by VitalyKravtsov2016** [comment]
Поправил:
https://github.com/VitalyKravtsov2016/OposWebkassa/releases/tag/0.82

**Comment by ErmacTheSoul** [comment]
спасибо
