### ISSUE TITLE
API, 2 ФР(учетки) на одном POS

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#81]
вопрос по множественному подключению

поддерживает ли драйвер сейчас одновременное подключение SHTRIH-M-OPOS-1 и SHTRIH-M-OPOS-2 ?
если нет, то можно ли сделать что бы поддерживал?
запускаем АСУ, к SHTRIH-M-OPOS-1 подключение проходит успешно, затем идет подключение к SHTRIH-M-OPOS-2 и получаем ошибку. поочередно через тестдрайвер подключение проходит успешно

[SHTRIH-M-OPOS-1_2024.10.24.log](https://github.com/user-attachments/files/17507115/SHTRIH-M-OPOS-1_2024.10.24.log)
[SHTRIH-M-OPOS-2_2024.10.24.log](https://github.com/user-attachments/files/17507117/SHTRIH-M-OPOS-2_2024.10.24.log)
[STOREPOINTIO-20241024.log](https://github.com/user-attachments/files/17507118/STOREPOINTIO-20241024.log)

**Comment by VitalyKravtsov2016** [comment]
Драйвер поддерживает одновременное подключение. 
В логе вижу ошибку: Касса не имеет активного активационного номера
Насколько я понимаю, это проблема настройки кассы.

**Comment by Dafafgh** [comment]
странно что отдельно подключение проходит успешно, даже с этой ошибкой. но в таком варианте - нет
написал про восстановление лицензии, позже проверю

**Comment by VitalyKravtsov2016** [comment]
Думаю, что дело в том, устройства настроены на один принтер. 
Посмотрю, что можно сделать.

**Comment by Dafafgh** [comment]
на всякий случай тест без ошибки. да на один и тот же принтер

[24.10.2024 18:36:28.004 ] [00066992] [DEBUG] ToleFiscalPrinter.ClaimDevice(10)
[24.10.2024 18:36:28.020 ] [00066992] [ERROR] OPOS_E_TIMEOUT, 0, "OPOS_E_TIMEOUT"
[24.10.2024 18:36:28.020 ] [00066992] [ERROR] OPOS_E_TIMEOUT, 0, "OPOS_E_TIMEOUT"

**Comment by VitalyKravtsov2016** [comment]
Поправил: 
https://github.com/VitalyKravtsov2016/OposWebkassa/releases/tag/0.83
