### ISSUE TITLE
Замена DATAMATRIX в слипе на обычный QR-код

### ISSUE THREAD

**Issue by mvelichko** [VitalyKravtsov2016/OposWebkassa#82]
Добрый день

Возник вопрос, у заказчика плохо считываются сканером слипы с datamatrix, они хотят чтобы в слипе был обычный QR код
Возможно ли каким-то образом это реализовать или может уже реализовано?

Сейчас так: 
ToleFiscalPrinter.DirectIO(7, 51, '77f80912c05e55833Mhss4hWHa28os7T37iQgJZqLghL9P6E8gvwMddxGLc=;DATAMATRIX;100;8;0;')=0

**Comment by VitalyKravtsov2016** [comment]
Добрый день. 
DIO_PRINT_BARCODE             = 7;
DIO_BARCODE_DATAMATRIX          = 51;
DIO_BARCODE_QRCODE              = 44;
Сейчас приложение вызывает DirectIO(DIO_PRINT_BARCODE, DIO_BARCODE_DATAMATRIX, "77f80912c05e55833Mhss4hWHa28os7T37iQgJZqLghL9P6E8gvwMddxGLc=;DATAMATRIX;100;8;0;")
То есть приложение явно указывает, что нужно печатать DATAMATRIX.
Автоматической замены параметров не реализовано. 

Варианты решения:
1. Поправить 1 строчку в приложении: заменить на DirectIO(DIO_PRINT_BARCODE, DIO_BARCODE_QRCODE,
2. Поправить драйвер, чтобы например, из двумерных кодов печатался только QR код. 
3. Подумать, почему плохо считывается DataMatrix - код плохо печатается или прохо читается..

**Comment by VitalyKravtsov2016** [comment]
[+] Добавлен параметр "Печатать QR код вместо DataMatrix" на страницу "Штрихкод" в программе настройки. 
https://github.com/VitalyKravtsov2016/OposWebkassa/releases/tag/0.84
