### ISSUE TITLE
Налоги. "НДС 0%" и "Без НДС"

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#86]
Выяснилось что сейчас неправильно отправляется тип налога "Без НДС"
Ардак написал что для ставки "Без НДС" нужно использовать:
"Tax" : 0,
 "TaxPercent" : null, 
 "TaxType" : 0,

а для "НДС 0%" 0:
"Tax" : 0,
 "TaxPercent" : 0, 
 "TaxType" : 0,

сейчас в обоих случаях отправляется "TaxPercent" : 0. а так же TaxType":100 вместо TaxType":0.
в таблице с налогами сейчас нельзя завести строку с null. можно добавить этот функционал?

[18.12.2024 16:42:07.698 ] [00000984] [DEBUG] ToleFiscalPrinter.PrintRecItem('nds0', 111, 1000, 1, 111, 'шт')=0
[18.12.2024 16:42:07.807 ] [00000984] [DEBUG] ToleFiscalPrinter.PrintRecItem('beznds', 222, 1000, **8**, 222, 'шт')=0
[18.12.2024 16:42:07.901 ] [00000984] [DEBUG] ToleFiscalPrinter.PrintRecItem('Кофе100', 25000, 1000, 4, 25000, 'шт')=0

{"Count":1,"Price":111,"TaxPercent":0,"Tax":0,"TaxType":100,"PositionName":"nds0"{"Count":1,"Price":222,"TaxPercent":**0**,"Tax":0,"TaxType":100,"PositionName":"beznds",{"Count":1,"Price":25000,"TaxPercent":12,"Tax":2678.57,"TaxType":100,"PositionName":"Кофе100"

![image](https://github.com/user-attachments/assets/a131883c-3569-4727-a7cb-a5dfa9318f18)
![image](https://github.com/user-attachments/assets/206f233a-acd4-4213-940b-9cf599f887e4)

[SHTRIH-M-OPOS-1_2024.12.18.log](https://github.com/user-attachments/files/18182068/SHTRIH-M-OPOS-1_2024.12.18.log)

**Comment by VitalyKravtsov2016** [comment]
Поправил:
https://github.com/VitalyKravtsov2016/OposWebkassa/releases/tag/0.92
