### ISSUE TITLE
Таблица соответствия единиц товара

### ISSUE THREAD

**Issue by Dafafgh** [VitalyKravtsov2016/OposWebkassa#87]
таблица соответствия доступна на первом устройстве SHTRIH-M-OPOS-1, а на SHTRIH-M-OPOS-2 недоступна. так должно быть?

![image](https://github.com/user-attachments/assets/75cad80f-3ef4-4411-8f1f-e473dea39d28)

**Comment by VitalyKravtsov2016** [comment]
Да, все параметры настраиваются для каждого устройства. 
Данные хранятся в реестре. Можно копировать данные реестра.

**Comment by Dafafgh** [comment]
если по первому экземпляру в интерфейсе можно выбрать "единицу сервера", то по второму нет. при чем данные в реестре есть, но в интерфейсе они не отображаются. по первому экземпляру все корректно отображается


![image](https://github.com/user-attachments/assets/51f9ac4d-614d-4449-b513-be12419da33a)
![image](https://github.com/user-attachments/assets/3827f9ca-7048-4d06-81f4-df6278541bb9)

**Comment by VitalyKravtsov2016** [comment]
Добрый день. 
Так произошло потому, что немного изменился формат хранения единиц измерения.
Предлагаю тестировать так: удалить все единицы, затем проверять. 
Также лучше к ошибке приложить REG файл ветки реестра, в которой находятся настройки.

**Comment by Dafafgh** [comment]
ок, но реестр я прикреплял

**Comment by VitalyKravtsov2016** [comment]
Точно, не заметил - извините.

**Comment by Dafafgh** [comment]
все я понял. не заметил
там одной ветки с самими ед. измерения на второй учетке нет..

**Comment by VitalyKravtsov2016** [comment]
Для чтения единиц с сервера можно нажать кнопку "Обновить".
